# Generated by Django 5.1.3 on 2024-12-03 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_review_book_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='book_cover',
        ),
    ]
