# Generated by Django 5.1.3 on 2024-12-04 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_favorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
