# Generated by Django 5.1.3 on 2024-12-05 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='price',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publish_date',
        ),
    ]
