# Generated by Django 5.1.3 on 2024-12-05 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_book_price_remove_book_publish_date'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
